version: '2'
services:
  web:
    build: .
    command:
      - node
      - "--inspect-brk=0.0.0.0"
      - "."
    volumes:
      - ./src/:/usr/app/nostratv_site/
      - /usr/app/nostratv_site/node_modules
    ports:
      - "3000:3000"
      - "9229:9229"
    environment:
      - PGID=1000
      - PUID=1000