version: '2'
services:
  web:
    build: .
    command: >
      sh -c "npm install
             npm start"
    volumes:
      - ./src/:/usr/app/nostratv_site/
      - ./shared_filesystem/:/usr/local/nostratv_site/
    ports:
      - "80:80"
    environment:
      - PGID=1000
      - PUID=1000
      - PORT=80