version: '2'
services:
  web:
    build: .
    command: npm start
    volumes:
      - ./src/:/usr/app/nostratv_site/
      - /usr/app/nostratv_site/node_modules
      - ./shared_filesystem/:/usr/local/nostratv_site/
    ports:
      - "80:80"
    environment:
      - PGID=1000
      - PUID=1000
      - PORT=80