version: '2'
services:
  web:
    environment:
      - PORT=80
    build: .
    command: npm start
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./shared_filesystem/:/usr/local/nostratv_site/
    environment:
      - PGID=1000
      - PUID=1000