version: '3.8'

services:
  postgres:
    image: postgres:15 
    container_name: local_postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}

